# ruff: noqa: E501 — data file: long strings are data, not code style
from decimal import Decimal
from typing import Any

ROLES = [
    {
        "name": "Director",
        "description": "System Director",
        "approval_limit": Decimal("999999999.99"),
    },
    {
        "name": "Manager",
        "description": "Branch Manager",
        "approval_limit": Decimal("1000000.00"),
    },
    {
        "name": "Loan Officer",
        "description": "Loan Officer",
        "approval_limit": Decimal("0.00"),
    },
    {
        "name": "Finance Officer",
        "description": "Finance Officer",
        "approval_limit": Decimal("100000.00"),
    },
    {
        "name": "System Admin",
        "description": "System Administrator",
        "approval_limit": Decimal("0.00"),
    },
    {
        "name": "Auditor",
        "description": "Auditor",
        "approval_limit": Decimal("0.00"),
    },
]

USERS = [
    {
        "employee_number": "FS-DIR001",
        "first_name": "System",
        "last_name": "Director",
        "email": "admin@enkaai.net",
        "password": "Faraja@2026",
        "role": "Director",
        "branch": "Head Office - Miritini",
    },
    {
        "employee_number": "FS-MGR001",
        "first_name": "Branch",
        "last_name": "Manager",
        "email": "manager@enkaai.net",
        "password": "Faraja@2026",
        "role": "Manager",
        "branch": "Mombasa",
    },
    {
        "employee_number": "FS-LO001",
        "first_name": "Loan",
        "last_name": "Officer",
        "email": "loanofficer@enkaai.net",
        "password": "Faraja@2026",
        "role": "Loan Officer",
        "branch": "Mombasa",
    },
    {
        "employee_number": "FS-ACC001",
        "first_name": "Finance",
        "last_name": "Officer",
        "email": "finance@enkaai.net",
        "password": "Faraja@2026",
        "role": "Finance Officer",
        "branch": "Head Office - Miritini",
    },
    {
        "employee_number": "FS-SYS001",
        "first_name": "System",
        "last_name": "Administrator",
        "email": "sysadmin@enkaai.net",
        "password": "Faraja@2026",
        "role": "System Admin",
        "branch": "Head Office - Miritini",
    },
    {
        "employee_number": "FS-AUD001",
        "first_name": "System",
        "last_name": "Auditor",
        "email": "auditor@enkaai.net",
        "password": "Faraja@2026",
        "role": "Auditor",
        "branch": "Head Office - Miritini",
    },
    {
        "employee_number": "FS-LO002",
        "first_name": "Mercy",
        "last_name": "Wambui Njoroge",
        "email": "loanofficer2@enkaai.net",
        "password": "Faraja@2026",
        "role": "Loan Officer",
        "branch": "Kilifi",
    },
    {
        "employee_number": "FS-MGR002",
        "first_name": "James",
        "last_name": "Karumba Mwangi",
        "email": "manager2@enkaai.net",
        "password": "Faraja@2026",
        "role": "Manager",
        "branch": "Kilifi",
    },
]

# ── Staging demo data ──────────────────────────────────────────────────────────
# Dates are stored as day offsets from "today" (see seed.py `days_ago`) so the
# seeded loan states (Performing / Arrears / Defaulter / Closed) stay meaningful
# no matter when the database is reseeded.

CLIENTS: list[dict[str, Any]] = [
    {
        "client_number": "CL-2026-001",
        "registered_days_ago": 36,
        "name": "Brian Misocho Moranga",
        "phone": "+254712345001",
        "email": "brian.moranga@gmail.com",
        "id_no": "21783451",
        "pin": "A005812364K",
        "gender": "Male",
        "marital_status": "Married",
        "occupation": "Welder / Metal Fabricator",
        "address": "Buxton Phase 4, Mombasa",
        "period_years": "6",
        "accommodation": "Own house",
        "landmark": "Near Buxton Primary School",
        "residential_maps_link": "https://maps.google.com/?q=-4.0435,39.6682",
        "business_maps_link": "https://maps.google.com/?q=-4.0500,39.6700",
        "spouse_name": "Janet Moranga",
        "spouse_id": "23456789",
        "spouse_phone": "+254712345051",
        "spouse_occupation": "Hairdresser",
        "spouse_address": "Buxton Phase 4, Mombasa",
        "applicant_dependants": [
            {"name": "Elvis Moranga", "age": 9, "relationship": "Son", "school": "Buxton Primary"},
            {"name": "Tina Moranga", "age": 5, "relationship": "Daughter", "school": "No"},
        ],
        "spouse_dependants": [],
        "dependants_count": "2",
        "dependants_ages": "9, 5",
        "school_going_count": "1",
        "school_details": "Elvis attends Buxton Primary School, std 4.",
        "next_of_kin_list": [
            {"name": "Samuel Moranga", "phone": "+254712345099", "relationship": "Brother", "address": "Likoni, Mombasa"}
        ],
        "business_name": "Moranga Metal Works",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Manufacturing",
        "business_landmark": "Jomvu Kuu",
        "business_years": "5",
        "business_location": "Jomvu Kuu, Mombasa",
        "estimated_asset_value": "180000",
        "guarantor_surname": "Omondi",
        "guarantor_first_name": "Collins",
        "guarantor_middle_name": "Onyango",
        "guarantor_id_no": "20193472",
        "guarantor_phone": "+254712345077",
        "guarantor_relationship": "Business Partner",
        "guarantor_address": "Jomvu Kuu, Mombasa",
        "guarantor_occupation": "Electrician",
        "guarantor_period_known": "4 years",
        "properties_list": [
            {"type": "Plot", "address": "Jomvu Kuu", "value": 400000, "ownership": "Jointly owned with spouse"}
        ],
        "branch": "Mombasa",
        "registered_by": "FS-LO001",
    },
    {
        "client_number": "CL-2026-002",
        "registered_days_ago": 21,
        "name": "Amina Hassan Juma",
        "phone": "+254723456002",
        "email": "amina.juma@yahoo.com",
        "id_no": "28347190",
        "pin": "A007419253P",
        "gender": "Female",
        "marital_status": "Married",
        "occupation": "Shopkeeper",
        "address": "Mikindani, Mombasa",
        "period_years": "8",
        "accommodation": "Renting",
        "landmark": "Mikindani Market",
        "residential_maps_link": "https://maps.google.com/?q=-4.0335,39.6501",
        "spouse_name": "Salim Juma",
        "spouse_id": "25918340",
        "spouse_phone": "+254723456052",
        "spouse_occupation": "Mason",
        "spouse_address": "Mikindani, Mombasa",
        "applicant_dependants": [
            {"name": "Rehema Salim", "age": 12, "relationship": "Daughter", "school": "Mikindani Girls"},
            {"name": "Hassan Salim", "age": 7, "relationship": "Son", "school": "Mikindani Primary"},
        ],
        "dependants_count": "2",
        "dependants_ages": "12, 7",
        "school_going_count": "2",
        "school_details": "Both children are in school.",
        "next_of_kin_list": [
            {"name": "Fatuma Hassan", "phone": "+254723456098", "relationship": "Mother", "address": "Mikindani, Mombasa"}
        ],
        "business_name": "Juma Duka & General Store",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Retail",
        "business_landmark": "Mikindani Market",
        "business_years": "6",
        "business_location": "Mikindani Market",
        "estimated_asset_value": "250000",
        "guarantor_surname": "Abdalla",
        "guarantor_first_name": "Said",
        "guarantor_middle_name": "",
        "guarantor_id_no": "24581203",
        "guarantor_phone": "+254723456076",
        "guarantor_relationship": "Uncle",
        "guarantor_address": "Mikindani, Mombasa",
        "guarantor_occupation": "Fishing",
        "guarantor_period_known": "10 years",
        "branch": "Mombasa",
        "registered_by": "FS-LO001",
    },
    {
        "client_number": "CL-2026-003",
        "registered_days_ago": 67,
        "name": "John Mwangi Kilonzo",
        "phone": "+254734567003",
        "email": None,
        "id_no": "24891567",
        "pin": "A009134527J",
        "gender": "Male",
        "marital_status": "Divorced",
        "occupation": "Boda Boda Rider",
        "address": "Kongowea, Mombasa",
        "period_years": "3",
        "accommodation": "Renting",
        "landmark": "Kongowea Stage",
        "applicant_dependants": [
            {"name": "Brian Kilonzo", "age": 14, "relationship": "Son", "school": "Kongowea Secondary"}
        ],
        "dependants_count": "1",
        "dependants_ages": "14",
        "school_going_count": "1",
        "school_details": "Brian is in form 2.",
        "next_of_kin_list": [
            {"name": "Lucy Kilonzo", "phone": "+254734567097", "relationship": "Sister", "address": "Kongowea, Mombasa"}
        ],
        "business_name": "Kilonzo Boda Boda",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Transport",
        "business_landmark": "Kongowea Stage",
        "business_years": "3",
        "business_location": "Kongowea, Mombasa",
        "estimated_asset_value": "95000",
        "guarantor_surname": "Kilonzo",
        "guarantor_first_name": "Peter",
        "guarantor_middle_name": "Munyao",
        "guarantor_id_no": "26458173",
        "guarantor_phone": "+254734567075",
        "guarantor_relationship": "Brother",
        "guarantor_address": "Mkomani, Mombasa",
        "guarantor_occupation": "Tuk Tuk Driver",
        "guarantor_period_known": "3 years",
        "branch": "Mombasa",
        "registered_by": "FS-LO001",
    },
    {
        "client_number": "CL-2026-004",
        "registered_days_ago": 16,
        "name": "Grace Wanjiru Njeri",
        "phone": "+254745678004",
        "email": "grace.njeri@gmail.com",
        "id_no": "30124568",
        "pin": "A011634827H",
        "gender": "Female",
        "marital_status": "Single",
        "occupation": "Salon Owner",
        "address": "Nyali Estate, Mombasa",
        "period_years": "4",
        "accommodation": "Renting",
        "landmark": "Nyali Centre",
        "next_of_kin_list": [
            {"name": "Esther Wanjiru", "phone": "+254745678096", "relationship": "Mother", "address": "Nyeri Town"}
        ],
        "business_name": "Grace Beauty Salon",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Beauty & Health",
        "business_landmark": "Nyali Centre",
        "business_years": "3",
        "business_location": "Nyali Centre",
        "estimated_asset_value": "120000",
        "guarantor_surname": "Kamau",
        "guarantor_first_name": "Nancy",
        "guarantor_middle_name": "Wairimu",
        "guarantor_id_no": "27891534",
        "guarantor_phone": "+254745678074",
        "guarantor_relationship": "Friend",
        "guarantor_address": "Nyali Estate",
        "guarantor_occupation": "Nurse",
        "guarantor_period_known": "2 years",
        "branch": "Mombasa",
        "registered_by": "FS-LO001",
    },
    {
        "client_number": "CL-2026-005",
        "registered_days_ago": 3,
        "name": "David Otieno Ochieng",
        "phone": "+254756789005",
        "email": "david.otieno@outlook.com",
        "id_no": "25671234",
        "pin": "A013481259F",
        "gender": "Male",
        "marital_status": "Married",
        "occupation": "Electronics Technician",
        "address": "Ganjoni, Mombasa",
        "period_years": "7",
        "accommodation": "Own house",
        "spouse_name": "Merceline Otieno",
        "spouse_id": "27645128",
        "spouse_phone": "+254756789055",
        "spouse_occupation": "Secretary",
        "spouse_address": "Ganjoni, Mombasa",
        "applicant_dependants": [
            {"name": "Kevin Otieno", "age": 10, "relationship": "Son", "school": "Ganjoni Primary"}
        ],
        "dependants_count": "1",
        "dependants_ages": "10",
        "school_going_count": "1",
        "school_details": "Kevin is in std 5.",
        "next_of_kin_list": [
            {"name": "Moses Ochieng", "phone": "+254756789095", "relationship": "Brother", "address": "Kisumu City"}
        ],
        "business_name": "Ochieng Electronics Repair",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Technology & Repairs",
        "business_landmark": "Ganjoni",
        "business_years": "5",
        "business_location": "Ganjoni, Mombasa",
        "estimated_asset_value": "200000",
        "guarantor_surname": "Ochieng",
        "guarantor_first_name": "Stephen",
        "guarantor_middle_name": "Onyango",
        "guarantor_id_no": "24157903",
        "guarantor_phone": "+254756789073",
        "guarantor_relationship": "Brother",
        "guarantor_address": "Ganjoni, Mombasa",
        "guarantor_occupation": "Teacher",
        "guarantor_period_known": "7 years",
        "branch": "Mombasa",
        "registered_by": "FS-LO001",
    },
    {
        "client_number": "CL-2026-006",
        "registered_days_ago": 6,
        "name": "Fatuma Mohammed Salim",
        "phone": "+254767890006",
        "email": "fatuma.salim@gmail.com",
        "id_no": "30987451",
        "pin": "A015709347D",
        "gender": "Female",
        "marital_status": "Married",
        "occupation": "Kiosk Owner",
        "address": "Mnarani, Kilifi",
        "period_years": "5",
        "accommodation": "Own house",
        "spouse_name": "Mohammed Salim",
        "spouse_id": "26581743",
        "spouse_phone": "+254767890056",
        "spouse_occupation": "Fisherman",
        "spouse_address": "Mnarani, Kilifi",
        "applicant_dependants": [
            {"name": "Aisha Mohammed", "age": 8, "relationship": "Daughter", "school": "Mnarani Primary"}
        ],
        "dependants_count": "1",
        "dependants_ages": "8",
        "school_going_count": "1",
        "school_details": "Aisha is in std 3.",
        "next_of_kin_list": [
            {"name": "Ali Salim", "phone": "+254767890094", "relationship": "Father", "address": "Mnarani, Kilifi"}
        ],
        "business_name": "Salim Kiosk & M-Pesa",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Retail",
        "business_landmark": "Mnarani Stage",
        "business_years": "4",
        "business_location": "Mnarani, Kilifi",
        "estimated_asset_value": "150000",
        "guarantor_surname": "Mwakideu",
        "guarantor_first_name": "Kazungu",
        "guarantor_middle_name": "",
        "guarantor_id_no": "28901452",
        "guarantor_phone": "+254767890072",
        "guarantor_relationship": "Neighbour",
        "guarantor_address": "Mnarani, Kilifi",
        "guarantor_occupation": "Carpenter",
        "guarantor_period_known": "4 years",
        "branch": "Kilifi",
        "registered_by": "FS-LO002",
    },
    {
        "client_number": "CL-2026-007",
        "registered_days_ago": 10,
        "name": "Peter Kipchoge Rono",
        "phone": "+254778901007",
        "email": "peter.rono@yahoo.com",
        "id_no": "24589163",
        "pin": "A017841536C",
        "gender": "Male",
        "marital_status": "Single",
        "occupation": "Poultry Farmer",
        "address": "Sokoni, Kilifi",
        "period_years": "2",
        "accommodation": "Renting",
        "landmark": "Kilifi Sokoni",
        "next_of_kin_list": [
            {"name": "Daniel Rono", "phone": "+254778901093", "relationship": "Father", "address": "Eldoret"}
        ],
        "business_name": "Rono Poultry Farm",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Agriculture",
        "business_landmark": "Kilifi Sokoni",
        "business_years": "2",
        "business_location": "Sokoni, Kilifi",
        "estimated_asset_value": "80000",
        "guarantor_surname": "Rono",
        "guarantor_first_name": "Samuel",
        "guarantor_middle_name": "Kipkoech",
        "guarantor_id_no": "27190458",
        "guarantor_phone": "+254778901071",
        "guarantor_relationship": "Brother",
        "guarantor_address": "Eldoret",
        "guarantor_occupation": "Accountant",
        "guarantor_period_known": "2 years",
        "branch": "Kilifi",
        "registered_by": "FS-LO002",
    },
    {
        "client_number": "CL-2026-008",
        "registered_days_ago": 96,
        "name": "Mary Akinyi Odhiambo",
        "phone": "+254789012008",
        "email": "mary.odhiambo@gmail.com",
        "id_no": "22145789",
        "pin": "A019831725B",
        "gender": "Female",
        "marital_status": "Widow",
        "occupation": "Tailor",
        "address": "Miritini, Mombasa",
        "period_years": "9",
        "accommodation": "Own house",
        "landmark": "Miritini SGR Station",
        "applicant_dependants": [
            {"name": "Cynthia Odhiambo", "age": 16, "relationship": "Daughter", "school": "Miritini Girls"},
            {"name": "Brian Odhiambo", "age": 13, "relationship": "Son", "school": "Miritini Secondary"},
        ],
        "dependants_count": "2",
        "dependants_ages": "16, 13",
        "school_going_count": "2",
        "school_details": "Cynthia is in form 3, Brian in form 1.",
        "next_of_kin_list": [
            {"name": "Rose Akinyi", "phone": "+254789012092", "relationship": "Sister", "address": "Miritini, Mombasa"}
        ],
        "business_name": "Mary's Tailoring & Fashion",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Textile & Fashion",
        "business_landmark": "Miritini SGR Station",
        "business_years": "7",
        "business_location": "Miritini, Mombasa",
        "estimated_asset_value": "300000",
        "guarantor_surname": "Nyaboke",
        "guarantor_first_name": "Brenda",
        "guarantor_middle_name": "Akinyi",
        "guarantor_id_no": "25613490",
        "guarantor_phone": "+254789012070",
        "guarantor_relationship": "Friend",
        "guarantor_address": "Miritini, Mombasa",
        "guarantor_occupation": "Nurse",
        "guarantor_period_known": "5 years",
        "branch": "Head Office - Miritini",
        "registered_by": "FS-LO001",
    },
    {
        "client_number": "CL-2026-009",
        "registered_days_ago": 2,
        "name": "Sofia Mwende Nzomo",
        "phone": "+254790123009",
        "email": None,
        "id_no": "28193465",
        "pin": "A021923847A",
        "gender": "Female",
        "marital_status": "Single",
        "occupation": "Vegetable Vendor",
        "address": "Kongowea Market, Mombasa",
        "period_years": "3",
        "accommodation": "Renting",
        "landmark": "Kongowea Market",
        "next_of_kin_list": [
            {"name": "Mary Nzomo", "phone": "+254790123091", "relationship": "Mother", "address": "Machakos"}
        ],
        "business_name": "Mwende Fresh Produce",
        "business_type": "Sole Proprietorship",
        "business_sector_custom": "Agriculture",
        "business_landmark": "Kongowea Market",
        "business_years": "3",
        "business_location": "Kongowea Market",
        "estimated_asset_value": "60000",
        "guarantor_surname": "Mutua",
        "guarantor_first_name": "Joseph",
        "guarantor_middle_name": "",
        "guarantor_id_no": "27013456",
        "guarantor_phone": "+254790123069",
        "guarantor_relationship": "Uncle",
        "guarantor_address": "Machakos",
        "guarantor_occupation": "Farmer",
        "guarantor_period_known": "3 years",
        "branch": "Mombasa",
        "registered_by": "FS-LO001",
    },
]

# Application fees for each loan (tier: new client → KES 800 ≤10k / 1,500 >10k).
# The last fee is deliberately UNVERIFIED so the Finance Officer has a
# verification task on staging.
FEE_PAYMENTS: list[dict[str, Any]] = [
    {"reference": "SEED-FEE-001", "client": "CL-2026-001", "loan": "LN-2026-001", "amount": "800", "mode": "Cash", "days_ago": 33, "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001", "notes": "Application fee (new client)"},
    {"reference": "SEED-FEE-002", "client": "CL-2026-002", "loan": "LN-2026-002", "amount": "800", "mode": "MPesa", "days_ago": 18, "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001", "notes": "Application fee (new client)"},
    {"reference": "SEED-FEE-003", "client": "CL-2026-003", "loan": "LN-2026-003", "amount": "800", "mode": "Cash", "days_ago": 64, "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001", "notes": "Application fee (new client)"},
    {"reference": "SEED-FEE-004", "client": "CL-2026-004", "loan": "LN-2026-004", "amount": "800", "mode": "MPesa", "days_ago": 14, "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001", "notes": "Application fee (new client)"},
    {"reference": "SEED-FEE-005", "client": "CL-2026-005", "loan": "LN-2026-005", "amount": "1500", "mode": "Cash", "days_ago": 2, "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001", "notes": "Application fee (new client)"},
    {"reference": "SEED-FEE-006", "client": "CL-2026-006", "loan": "LN-2026-006", "amount": "1500", "mode": "BankTransfer", "days_ago": 5, "recorded_by": "FS-LO002", "verified": True, "verified_by": "FS-MGR002", "notes": "Application fee (new client)"},
    {"reference": "SEED-FEE-007", "client": "CL-2026-007", "loan": "LN-2026-007", "amount": "800", "mode": "Cash", "days_ago": 9, "recorded_by": "FS-LO002", "verified": True, "verified_by": "FS-MGR002", "notes": "Application fee (new client)"},
    {"reference": "SEED-FEE-008", "client": "CL-2026-008", "loan": "LN-2026-008", "amount": "800", "mode": "Cash", "days_ago": 93, "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001", "notes": "Application fee (new client)"},
    {"reference": "SEED-FEE-009", "client": "CL-2026-009", "loan": None, "amount": "800", "mode": "MPesa", "days_ago": 1, "recorded_by": "FS-LO001", "verified": False, "verified_by": None, "notes": "Application fee — awaiting verification"},
]

LOANS: list[dict[str, Any]] = [
    # ── Disbursed, 3 days past due, 2 of 4 installments paid → Past Maturity ──
    {
        "loan_number": "LN-2026-001",
        "client": "CL-2026-001",
        "product": "Faraja 4 Weeks",
        "amount": "8000",
        "sector": "Manufacturing",
        "branch": "Mombasa",
        "submitted_by": "FS-LO001",
        "submitted_days_ago": 35,
        "approved_by": "FS-MGR001",
        "approved_days_ago": 33,
        "approval_note": "Business verified at Jomvu Kuu site visit.",
        "disbursed_by": "FS-MGR001",
        "disbursed_days_ago": 31,
        "status": "Disbursed",
        "notes": "Metal fabrication business, steady income.",
        "fees_paid": True,
    },
    # ── Disbursed, on schedule → Performing (plus one unverified repayment) ──
    {
        "loan_number": "LN-2026-002",
        "client": "CL-2026-002",
        "product": "Faraja 4 Weeks",
        "amount": "10000",
        "sector": "Retail",
        "branch": "Mombasa",
        "submitted_by": "FS-LO001",
        "submitted_days_ago": 20,
        "approved_by": "FS-MGR001",
        "approved_days_ago": 18,
        "approval_note": "Duka stock valuation done, client is a repeat applicant.",
        "disbursed_by": "FS-MGR001",
        "disbursed_days_ago": 17,
        "status": "Disbursed",
        "notes": "General store with M-Pesa till.",
    },
    # ── Disbursed, 35 days past due, only 1 of 4 installments paid → Defaulter ──
    {
        "loan_number": "LN-2026-003",
        "client": "CL-2026-003",
        "product": "Faraja 4 Weeks",
        "amount": "6000",
        "sector": "Transport",
        "branch": "Mombasa",
        "submitted_by": "FS-LO001",
        "submitted_days_ago": 66,
        "approved_by": "FS-MGR001",
        "approved_days_ago": 64,
        "approval_note": "Boda boda logbook confirmed.",
        "disbursed_by": "FS-MGR001",
        "disbursed_days_ago": 63,
        "status": "Disbursed",
        "notes": "Client stopped answering calls since July.",
    },
    # ── Disbursed, first installment due & unpaid → Arrears ──
    {
        "loan_number": "LN-2026-004",
        "client": "CL-2026-004",
        "product": "Faraja 4 Weeks",
        "amount": "5000",
        "sector": "Beauty & Health",
        "branch": "Mombasa",
        "submitted_by": "FS-LO001",
        "submitted_days_ago": 15,
        "approved_by": "FS-MGR001",
        "approved_days_ago": 14,
        "approval_note": "Salon equipment purchase, verified.",
        "disbursed_by": "FS-MGR001",
        "disbursed_days_ago": 13,
        "status": "Disbursed",
        "notes": "Awaiting first repayment.",
    },
    # ── Pending approval (fee verified & linked) ──
    {
        "loan_number": "LN-2026-005",
        "client": "CL-2026-005",
        "product": "Faraja 4 Weeks",
        "amount": "12000",
        "sector": "Technology & Repairs",
        "branch": "Mombasa",
        "submitted_by": "FS-LO001",
        "submitted_days_ago": 2,
        "status": "Pending",
        "notes": "Electronics spares restocking.",
    },
    # ── Approved, awaiting disbursement ──
    {
        "loan_number": "LN-2026-006",
        "client": "CL-2026-006",
        "product": "Faraja 5 Weeks",
        "amount": "15000",
        "sector": "Retail",
        "branch": "Kilifi",
        "submitted_by": "FS-LO002",
        "submitted_days_ago": 5,
        "approved_by": "FS-MGR002",
        "approved_days_ago": 3,
        "approval_note": "Kiosk expansion plan approved.",
        "status": "Approved",
        "notes": "M-Pesa float top-up and stock.",
    },
    # ── Rejected ──
    {
        "loan_number": "LN-2026-007",
        "client": "CL-2026-007",
        "product": "Faraja 5 Weeks",
        "amount": "4500",
        "sector": "Agriculture",
        "branch": "Kilifi",
        "submitted_by": "FS-LO002",
        "submitted_days_ago": 9,
        "approved_by": "FS-MGR002",
        "approved_days_ago": 7,
        "rejection_reason": "Insufficient business documentation; farm records not verifiable.",
        "status": "Rejected",
        "notes": "Client may reapply with KRA records.",
    },
    # ── Fully repaid & closed (repeat client → cheaper fee on next loan) ──
    {
        "loan_number": "LN-2026-008",
        "client": "CL-2026-008",
        "product": "Faraja 5 Weeks",
        "amount": "10000",
        "sector": "Textile & Fashion",
        "branch": "Head Office - Miritini",
        "submitted_by": "FS-LO001",
        "submitted_days_ago": 95,
        "approved_by": "FS-MGR001",
        "approved_days_ago": 93,
        "approval_note": "Sewing machine upgrade approved.",
        "disbursed_by": "FS-MGR001",
        "disbursed_days_ago": 92,
        "status": "Closed",
        "notes": "Paid in full, loan closed on time.",
    },
]

# Repayments are resolved against loans in seed.py; `verified` repayment dates
# must align with installment due dates (weekly from disbursement).
REPAYMENTS: list[dict[str, Any]] = [
    # LN-2026-001 — 2 of 4 installments paid
    {"loan": "LN-2026-001", "amount": "2400", "mode": "Cash", "days_ago": 24, "reference": "SEED-RPY-001", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    {"loan": "LN-2026-001", "amount": "2400", "mode": "MPesa", "days_ago": 17, "reference": "SEED-RPY-002", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    # LN-2026-002 — 2 of 4 installments paid (installment 3 covered, unverified)
    {"loan": "LN-2026-002", "amount": "3000", "mode": "Cash", "days_ago": 10, "reference": "SEED-RPY-003", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    {"loan": "LN-2026-002", "amount": "3000", "mode": "MPesa", "days_ago": 3, "reference": "SEED-RPY-004", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    {"loan": "LN-2026-002", "amount": "1000", "mode": "MPesa", "days_ago": 1, "reference": "SEED-RPY-005", "recorded_by": "FS-LO001", "verified": False, "verified_by": None},
    # LN-2026-003 — 1 of 4 installments paid
    {"loan": "LN-2026-003", "amount": "1800", "mode": "Cash", "days_ago": 56, "reference": "SEED-RPY-006", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    # LN-2026-004 — none paid (Arrears)
    # LN-2026-008 — fully paid (5 installments)
    {"loan": "LN-2026-008", "amount": "2600", "mode": "Cash", "days_ago": 85, "reference": "SEED-RPY-007", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    {"loan": "LN-2026-008", "amount": "2600", "mode": "Cash", "days_ago": 78, "reference": "SEED-RPY-008", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    {"loan": "LN-2026-008", "amount": "2600", "mode": "MPesa", "days_ago": 71, "reference": "SEED-RPY-009", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    {"loan": "LN-2026-008", "amount": "2600", "mode": "MPesa", "days_ago": 64, "reference": "SEED-RPY-010", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
    {"loan": "LN-2026-008", "amount": "2600", "mode": "Cash", "days_ago": 57, "reference": "SEED-RPY-011", "recorded_by": "FS-LO001", "verified": True, "verified_by": "FS-ACC001"},
]
