"""penalty_snapshots table

Revision ID: 3275d243045a
Revises: 0482b1f8e6ef
Create Date: 2026-08-17 22:15:57.233332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3275d243045a'
down_revision: Union[str, Sequence[str], None] = '0482b1f8e6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalty_snapshots',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('outstanding', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'snapshot_date', name='uq_penalty_snapshot_loan_date')
    )
    op.create_index(op.f('ix_penalty_snapshots_loan_id'), 'penalty_snapshots', ['loan_id'], unique=False)
    op.create_index(op.f('ix_penalty_snapshots_snapshot_date'), 'penalty_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_penalty_snapshots_snapshot_date'), table_name='penalty_snapshots')
    op.drop_index(op.f('ix_penalty_snapshots_loan_id'), table_name='penalty_snapshots')
    op.drop_table('penalty_snapshots')
    # ### end Alembic commands ###
