"""add expenses table

Revision ID: 3593c62a6020
Revises: c04609b1b091
Create Date: 2026-08-17 14:31:59.361842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3593c62a6020"
down_revision: str | Sequence[str] | None = "c04609b1b091"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "SALARIES",
                "RENT",
                "UTILITIES",
                "TRANSPORT",
                "MARKETING",
                "STATIONERY",
                "OPERATIONS",
                "OTHER",
                name="expensecategory",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column(
            "mode",
            postgresql.ENUM(
                "CASH",
                "MPESA",
                "BANK_TRANSFER",
                "CHEQUE",
                "OTHER",
                name="paymentmode",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("recorded_by_id", sa.UUID(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_by_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recorded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["verified_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_branch_id"), "expenses", ["branch_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_branch_id"), table_name="expenses")
    op.drop_table("expenses")
    # ### end Alembic commands ###
