"""loan status override fields

Revision ID: 697c72921ff3
Revises: 3593c62a6020
Create Date: 2026-08-17 17:37:01.531063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697c72921ff3'
down_revision: Union[str, Sequence[str], None] = '3593c62a6020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('status_override', sa.String(length=30), nullable=True))
    op.add_column('loans', sa.Column('status_override_by_id', sa.UUID(), nullable=True))
    op.add_column('loans', sa.Column('status_override_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'loans', 'users', ['status_override_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'status_override_at')
    op.drop_column('loans', 'status_override_by_id')
    op.drop_column('loans', 'status_override')
    # ### end Alembic commands ###
