"""add user profile fields

Revision ID: 6f2942b8aaea
Revises: 9e2b1a7c4d5f
Create Date: 2026-08-07 17:05:43.899214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2942b8aaea'
down_revision: Union[str, Sequence[str], None] = '9e2b1a7c4d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('id_no', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('profile_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'id_no')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
