"""add notification_prefs

Revision ID: 71f36ff96244
Revises: 6f2942b8aaea
Create Date: 2026-08-07 20:13:31.553916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71f36ff96244'
down_revision: Union[str, Sequence[str], None] = '6f2942b8aaea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_prefs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_prefs_user_id'), 'notification_prefs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_prefs_user_id'), table_name='notification_prefs')
    op.drop_table('notification_prefs')
    # ### end Alembic commands ###
