"""add_p2_business_models

Revision ID: 78fd0153f296
Revises: ac3d7f2d3767
Create Date: 2026-08-06 15:35:40.458353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fd0153f296'
down_revision: Union[str, Sequence[str], None] = 'ac3d7f2d3767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_products',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('product_type', sa.Enum('FARAJA_4_WEEKS', 'FARAJA_5_WEEKS', 'LUMPSUM', name='loanproducttype'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('penalty_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('penalty_interval_days', sa.Integer(), nullable=False),
    sa.Column('max_penalty_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_products_name'), 'loan_products', ['name'], unique=True)
    op.create_table('clients',
    sa.Column('client_number', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id_no', sa.String(length=50), nullable=True),
    sa.Column('pin', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('period_years', sa.String(length=20), nullable=True),
    sa.Column('accommodation', sa.String(length=50), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('residential_maps_link', sa.String(length=500), nullable=True),
    sa.Column('business_maps_link', sa.String(length=500), nullable=True),
    sa.Column('spouse_name', sa.String(length=200), nullable=True),
    sa.Column('spouse_id', sa.String(length=50), nullable=True),
    sa.Column('spouse_phone', sa.String(length=30), nullable=True),
    sa.Column('spouse_occupation', sa.String(length=150), nullable=True),
    sa.Column('spouse_address', sa.String(length=255), nullable=True),
    sa.Column('applicant_dependants', sa.JSON(), nullable=True),
    sa.Column('spouse_dependants', sa.JSON(), nullable=True),
    sa.Column('dependants_count', sa.String(length=10), nullable=True),
    sa.Column('dependants_ages', sa.String(length=100), nullable=True),
    sa.Column('school_going_count', sa.String(length=10), nullable=True),
    sa.Column('school_details', sa.Text(), nullable=True),
    sa.Column('next_of_kin_list', sa.JSON(), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('business_sector_custom', sa.String(length=150), nullable=True),
    sa.Column('business_landmark', sa.String(length=255), nullable=True),
    sa.Column('business_years', sa.String(length=20), nullable=True),
    sa.Column('business_location', sa.String(length=255), nullable=True),
    sa.Column('guarantor_surname', sa.String(length=100), nullable=True),
    sa.Column('guarantor_first_name', sa.String(length=100), nullable=True),
    sa.Column('guarantor_middle_name', sa.String(length=100), nullable=True),
    sa.Column('guarantor_id_no', sa.String(length=50), nullable=True),
    sa.Column('guarantor_phone', sa.String(length=30), nullable=True),
    sa.Column('guarantor_relationship', sa.String(length=100), nullable=True),
    sa.Column('guarantor_address', sa.String(length=255), nullable=True),
    sa.Column('guarantor_occupation', sa.String(length=150), nullable=True),
    sa.Column('guarantor_period_known', sa.String(length=50), nullable=True),
    sa.Column('properties_list', sa.JSON(), nullable=True),
    sa.Column('applicant_id_photo', sa.String(length=500), nullable=True),
    sa.Column('applicant_passport_photo', sa.String(length=500), nullable=True),
    sa.Column('guarantor_id_photo', sa.String(length=500), nullable=True),
    sa.Column('guarantor_passport_photo', sa.String(length=500), nullable=True),
    sa.Column('applicant_signature', sa.String(length=500), nullable=True),
    sa.Column('guarantor_signature', sa.String(length=500), nullable=True),
    sa.Column('registration_fee', sa.Float(), nullable=True),
    sa.Column('application_fee', sa.Float(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('registered_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_branch_id'), 'clients', ['branch_id'], unique=False)
    op.create_index(op.f('ix_clients_client_number'), 'clients', ['client_number'], unique=True)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('loans',
    sa.Column('loan_number', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('loan_product_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_repayable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('application_fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DISBURSED', 'REJECTED', 'CLOSED', name='loanstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('disbursed_by_id', sa.UUID(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('disbursed_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['disbursed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_product_id'], ['loan_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_branch_id'), 'loans', ['branch_id'], unique=False)
    op.create_index(op.f('ix_loans_client_id'), 'loans', ['client_id'], unique=False)
    op.create_index(op.f('ix_loans_loan_number'), 'loans', ['loan_number'], unique=True)
    op.create_table('installments',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'MISSED', 'LATE', name='installmentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installments_loan_id'), 'installments', ['loan_id'], unique=False)
    op.create_table('repayments',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.Enum('CASH', 'MPESA', 'BANK_TRANSFER', 'CHEQUE', 'OTHER', name='paymentmode'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayments_client_id'), 'repayments', ['client_id'], unique=False)
    op.create_index(op.f('ix_repayments_loan_id'), 'repayments', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repayments_loan_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_client_id'), table_name='repayments')
    op.drop_table('repayments')
    op.drop_index(op.f('ix_installments_loan_id'), table_name='installments')
    op.drop_table('installments')
    op.drop_index(op.f('ix_loans_loan_number'), table_name='loans')
    op.drop_index(op.f('ix_loans_client_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_branch_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_branch_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_loan_products_name'), table_name='loan_products')
    op.drop_table('loan_products')
    # ### end Alembic commands ###
