"""add_business_photo

Revision ID: a9213f2dd78e
Revises: 9c48321056f4
Create Date: 2026-08-06 16:37:45.843477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9213f2dd78e'
down_revision: Union[str, Sequence[str], None] = '9c48321056f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('business_photo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'business_photo')
    # ### end Alembic commands ###
