"""add fee_payments table

Revision ID: d3aa1130642d
Revises: 56abb241f073
Create Date: 2026-08-07 02:23:10.017419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd3aa1130642d'
down_revision: Union[str, Sequence[str], None] = '56abb241f073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_payments',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('fee_type', postgresql.ENUM('APPLICATION', name='feetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('mode', postgresql.ENUM('CASH', 'MPESA', 'BANK_TRANSFER', 'CHEQUE', 'OTHER', name='paymentmode', create_type=False), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', name='uq_fee_payments_reference')
    )
    op.create_index(op.f('ix_fee_payments_client_id'), 'fee_payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_loan_id'), 'fee_payments', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_payments_loan_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_client_id'), table_name='fee_payments')
    op.drop_table('fee_payments')
    # ### end Alembic commands ###
